version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: build-react
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: build-dotnet
    ports:
      - "5000:80"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: YourPassword123
      ACCEPT_EULA: Y
    volumes:
      - db-data:/var/opt/mssql
    ports:
      - "1433:1433"

volumes:
  db-data:
